### ISSUE TITLE
Error: class MFRC522' has no member named 'GET_ID

### ISSUE THREAD

**Issue by AsankaD7** [goodvubo/RFID#1]
I used cardRead.ino file. I was getting some error in below 

CardReader:52: error: 'class MFRC522' has no member named 'GET_ID'
  a = mfrc522.GET_ID(&(mfrc522.uid));

how can I fixed it?

**Comment by goodvubo** [comment]
hope i'm not too late :P
busy making something.
copy the vubo folder to arduino libraries folder. then u can get that as
library from the arduino ide. add the new "vubo" library to the ino file.
i changed the files for ease of use. Ofcourse, there r other ways to make
it work. hope it helps.
